const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('kuan', {
  getFeed: (params) => ipcRenderer.invoke('api:getFeed', params),
  getFeedPage: (params) => ipcRenderer.invoke('api:getFeedPage', params),
  getFeedDetail: (id) => ipcRenderer.invoke('api:getFeedDetail', id),
  getReplyList: (id, page) => ipcRenderer.invoke('api:getReplyList', id, page),
  login: (username, password, captcha, requestHash, loginType) => ipcRenderer.invoke('api:login', username, password, captcha, requestHash, loginType),
  sendSms: (phone, requestHash) => ipcRenderer.invoke('api:sendSms', phone, requestHash),
  checkLoginInfo: () => ipcRenderer.invoke('api:checkLoginInfo'),
  logout: () => ipcRenderer.invoke('api:logout'),
  getUser: () => ipcRenderer.invoke('api:getUser'),
  isLoggedIn: () => ipcRenderer.invoke('api:isLoggedIn'),
  getUserInfo: (uid) => ipcRenderer.invoke('api:getUserInfo', uid),
  search: (keyword, page, type, sort) => ipcRenderer.invoke('api:search', keyword, page, type, sort),
  searchSuggest: (keyword) => ipcRenderer.invoke('api:searchSuggest', keyword),
  getTopicDetail: (tag) => ipcRenderer.invoke('api:getTopicDetail', tag),
  getTopicFeedList: (tag, page, listType) => ipcRenderer.invoke('api:getTopicFeedList', tag, page, listType),
  // 用户主页
  getUserSpace: (uid) => ipcRenderer.invoke('api:getUserSpace', uid),
  getUserFeedList: (uid, page) => ipcRenderer.invoke('api:getUserFeedList', uid, page),
  getUserReplyList: (uid, page) => ipcRenderer.invoke('api:getUserReplyList', uid, page),
  // 动态/消息/通知
  getMyFeedList: (page) => ipcRenderer.invoke('api:getMyFeedList', page),
  getFollowFeedList: (page) => ipcRenderer.invoke('api:getFollowFeedList', page),
  getNotificationList: (page) => ipcRenderer.invoke('api:getNotificationList', page),
  getMessageList: (page) => ipcRenderer.invoke('api:getMessageList', page),
  getUnreadCount: () => ipcRenderer.invoke('api:getUnreadCount'),
  readNotification: (id) => ipcRenderer.invoke('api:readNotification', id),
  getInit: () => ipcRenderer.invoke('api:getInit'),
  getHeadline: (page) => ipcRenderer.invoke('api:getHeadline', page),
  fetch: (path) => ipcRenderer.invoke('api:fetch', path),
  fetchCaptchaImage: (requestHash) => ipcRenderer.invoke('api:fetchCaptchaImage', requestHash),
  webLogin: () => ipcRenderer.invoke('api:webLogin'),
  // 动态操作
  likeFeed: (id) => ipcRenderer.invoke('api:likeFeed', id),
  unlikeFeed: (id) => ipcRenderer.invoke('api:unlikeFeed', id),
  likeReply: (id) => ipcRenderer.invoke('api:likeReply', id),
  unlikeReply: (id) => ipcRenderer.invoke('api:unlikeReply', id),
  followUser: (uid) => ipcRenderer.invoke('api:followUser', uid),
  unfollowUser: (uid) => ipcRenderer.invoke('api:unfollowUser', uid),
  favoriteFeed: (id) => ipcRenderer.invoke('api:favoriteFeed', id),
  reportFeed: (id, reason) => ipcRenderer.invoke('api:reportFeed', id, reason),
  deleteFeed: (id) => ipcRenderer.invoke('api:deleteFeed', id),
  postReply: (id, message, type) => ipcRenderer.invoke('api:postReply', id, message, type),
  getReplyListSorted: (id, page, listType) => ipcRenderer.invoke('api:getReplyListSorted', id, page, listType),
  createFeed: (data) => ipcRenderer.invoke('api:createFeed', data),
  store: {
    get: (key) => ipcRenderer.invoke('store:get', key),
    set: (key, val) => ipcRenderer.invoke('store:set', key, val),
  },
  clearCache: () => ipcRenderer.invoke('clearCache'),
  openExternal: (url) => ipcRenderer.invoke('openExternal', url),
});
